### ISSUE TITLE
Sublime Text too

### ISSUE THREAD

**Issue by JohnGravesDM** [whizzml/whizzml-mode#1]
http://docs.sublimetext.info/en/latest/extensibility/syntaxdefs.html

**Comment by osroca** [comment]
@JohnGravesDM we have created a package for Sublime Text 3. It has support for WhizzML syntax highlighting and auto-complete. Please find it out in the repo [whizzml/whizzml-sublime](https://github.com/whizzml/whizzml-sublime).

We have opened a [PR](https://github.com/wbond/package_control_channel/pull/5577) in order to publish it in https://packagecontrol.io, but if you want to try it now you can do it by adding this repo to package control by running the command _Package Control: Add Repository_ and pasting the URL https://github.com/whizzml/whizzml-sublime. Then you will be able to find the package with the command _Package Control: Install Package > whizzml-sublime_.

**Comment by osroca** [comment]
@JohnGravesDM finally our PR in packagecontrol.io have been approved so you can install whizzml-sublime following the regular workflow of package control (no need to add out repository). Please, find the instructions in [whizzml/whizzml-sublime#README](https://github.com/whizzml/whizzml-sublime#using-package-control).
